apiVersion: v1
kind: Namespace
metadata:
  name: dui
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dui
  namespace: dui
  labels:
    app: dui
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: dui
    spec:
      containers:
        - name: master
          image: caladreas/buming:0.2.0
          env:
            - name: MEMBERSHIP_UPDATE_RATE_IN_MILLIS
              value: 2500
          ports:
            - name: external
              containerPort: 7777
            - name: interal
              containerPort: 7781
            - name: group
              containerPort: 7791
            - name: hc
              containerPort: 8888
          lifecycle:
            preStop:
              exec:
                command: ["killall", "java" , "-INT"]
          readinessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              memory: "50Mi"
              cpu: 0.02
            requests:
              memory: "50Mi"
              cpu: 0.02
      terminationGracePeriodSeconds: 60

---
kind: Service
apiVersion: v1
metadata:
  name: dui
  namespace: dui
spec:
  selector:
    app: dui
  ports:
  - protocol: TCP
    port: 7777
  type: NodePort
