apiVersion: v1
kind: Namespace
metadata:
  name: vasimos
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dui-deployment
  namespace: default
  labels:
    k8s-app: dui
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: dui
    spec:
      containers:
        - name: master
          image: caladreas/buming:0.2.0
          ports:
            - name: http
              containerPort: 7777
          lifecycle:
            preStop:
              exec:
                command: ["killall", "java" , "-INT"]
          readinessProbe:
            httpGet:
              path: /
              port: 8888
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /
              port: 8888
      terminationGracePeriodSeconds: 60

---
kind: Service
apiVersion: v1
metadata:
  name: dui-service
  namespace: default
spec:
  selector:
    k8s-app: dui
  ports:
  - protocol: TCP
    port: 7777
  type: NodePort
