version: "3.5"

services:
  yi:
    image: dui
    build: .
    stop_signal: SIGINT
    networks:
      - dui
  er:
    image: dui
    stop_signal: SIGINT
    networks:
      - dui
  san:
    image: dui
    stop_signal: SIGINT
    networks:
      - dui

# Overlay doesn't support multicast
# https://github.com/docker/libnetwork/issues/552 / https://github.com/docker/libnetwork/issues/552#issuecomment-343067616
# https://github.com/moby/moby/issues/3043
# driver:
#  driver-opts:encrypted
networks:
  dui:
    driver: macvlan
    attachable: true
