version: "3.5"

services:
  yi:
    image: dui
    build: .
    networks:
      - dui
  er:
    image: dui
    networks:
      - dui
  san:
    image: dui
    networks:
      - dui

networks:
  dui:
    driver: overlay
    attachable: true
