version: "3.5"

services:
  yi:
    image: dui
    build: .
    networks:
      - dui
  er:
    image: dui
    networks:
      - dui
  san:
    image: dui
    networks:
      - dui

# Overlay doesn't support multicast
# https://github.com/docker/libnetwork/issues/552 / https://github.com/docker/libnetwork/issues/552#issuecomment-343067616
# https://github.com/moby/moby/issues/3043
networks:
  dui:
    driver: macvlan
    attachable: true
