apiVersion: v1
kind: Namespace
metadata:
  name: dui
  labels:
    environment: staging
    purpose: dui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dui
  namespace: dui
  labels:
    app: dui
    distribution: server
    language: java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dui
      distribution: server
      language: java
  template:
    metadata:
      labels:
        app: dui
        distribution: server
        language: java
    spec:
      containers:
        - name: master
          image: caladreas/buming:0.4.0
          env:
            - name: MEMBERSHIP_UPDATE_RATE_IN_MILLIS
              value: "2500"
          ports:
            - name: external
              containerPort: 7777
            - name: interal
              containerPort: 7781
            - name: group
              containerPort: 7791
            - name: hc
              containerPort: 8888
          lifecycle:
            preStop:
              exec:
                command: ["killall", "java" , "-INT"]
          readinessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 25
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 45
            periodSeconds: 30
          resources:
            limits:
              memory: "50Mi"
              cpu: "0.02"
            requests:
              memory: "50Mi"
              cpu: "0.02"
      terminationGracePeriodSeconds: 60

---
kind: Service
apiVersion: v1
metadata:
  name: dui
  namespace: dui
spec:
  selector:
    app: dui
    distribution: server
    language: java
  ports:
  - protocol: TCP
    port: 7777
  type: NodePort
