kind: Service
apiVersion: v1
metadata:
    name: {{ include "dui.fullname" . }}
    labels:
        app: {{ include "dui.name" . }}
        chart: {{ include "dui.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
spec:
    selector:
        app: {{ include "dui.name" . }}
        release: {{ .Release.Name }}
    ports:
    - protocol: TCP
      port: 7777
    type: NodePort
